sudo: required
services:
  - docker

before_install: 
  - docker build -t prasanjitb/docker-react -f Dockerfile.dev .

script:
  - docker run prasanjitb/docker-react npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-aws"
  env: "DockerReactAws-env"
  bucket_name: "elasticbeanstalk-us-east-1-000052450482"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"